// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	model "fundamental-payroll-gin/model"

	mock "github.com/stretchr/testify/mock"
)

// EmployeeRMQPubRepoI is an autogenerated mock type for the EmployeeRMQPubRepoI type
type EmployeeRMQPubRepoI struct {
	mock.Mock
}

// Add provides a mock function with given fields: req
func (_m *EmployeeRMQPubRepoI) Add(req *model.Employee) (*model.Employee, error) {
	ret := _m.Called(req)

	var r0 *model.Employee
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Employee) (*model.Employee, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*model.Employee) *model.Employee); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Employee)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Employee) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewEmployeeRMQPubRepoI interface {
	mock.TestingT
	Cleanup(func())
}

// NewEmployeeRMQPubRepoI creates a new instance of EmployeeRMQPubRepoI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEmployeeRMQPubRepoI(t mockConstructorTestingTNewEmployeeRMQPubRepoI) *EmployeeRMQPubRepoI {
	mock := &EmployeeRMQPubRepoI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
