// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	amqp091 "github.com/rabbitmq/amqp091-go"
	mock "github.com/stretchr/testify/mock"
)

// InterfaceRMQ is an autogenerated mock type for the InterfaceRMQ type
type InterfaceRMQ struct {
	mock.Mock
}

// ChClose provides a mock function with given fields:
func (_m *InterfaceRMQ) ChClose() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConnClose provides a mock function with given fields:
func (_m *InterfaceRMQ) ConnClose() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Publish provides a mock function with given fields: exchangeName, routingKeyPub, dataBytes
func (_m *InterfaceRMQ) Publish(exchangeName string, routingKeyPub string, dataBytes []byte) error {
	ret := _m.Called(exchangeName, routingKeyPub, dataBytes)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, []byte) error); ok {
		r0 = rf(exchangeName, routingKeyPub, dataBytes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Subscribe provides a mock function with given fields: exchangeName, routingKeyCon, autoAck
func (_m *InterfaceRMQ) Subscribe(exchangeName string, routingKeyCon string, autoAck bool) (<-chan amqp091.Delivery, error) {
	ret := _m.Called(exchangeName, routingKeyCon, autoAck)

	var r0 <-chan amqp091.Delivery
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, bool) (<-chan amqp091.Delivery, error)); ok {
		return rf(exchangeName, routingKeyCon, autoAck)
	}
	if rf, ok := ret.Get(0).(func(string, string, bool) <-chan amqp091.Delivery); ok {
		r0 = rf(exchangeName, routingKeyCon, autoAck)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan amqp091.Delivery)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, bool) error); ok {
		r1 = rf(exchangeName, routingKeyCon, autoAck)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewInterfaceRMQ interface {
	mock.TestingT
	Cleanup(func())
}

// NewInterfaceRMQ creates a new instance of InterfaceRMQ. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInterfaceRMQ(t mockConstructorTestingTNewInterfaceRMQ) *InterfaceRMQ {
	mock := &InterfaceRMQ{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
