// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	model "fundamental-payroll-gin/model"

	mock "github.com/stretchr/testify/mock"
)

// PayrollRMQPubRepoI is an autogenerated mock type for the PayrollRMQPubRepoI type
type PayrollRMQPubRepoI struct {
	mock.Mock
}

// Add provides a mock function with given fields: req
func (_m *PayrollRMQPubRepoI) Add(req *model.Payroll) (*model.Payroll, error) {
	ret := _m.Called(req)

	var r0 *model.Payroll
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Payroll) (*model.Payroll, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*model.Payroll) *model.Payroll); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Payroll)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Payroll) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPayrollRMQPubRepoI interface {
	mock.TestingT
	Cleanup(func())
}

// NewPayrollRMQPubRepoI creates a new instance of PayrollRMQPubRepoI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPayrollRMQPubRepoI(t mockConstructorTestingTNewPayrollRMQPubRepoI) *PayrollRMQPubRepoI {
	mock := &PayrollRMQPubRepoI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
