// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	model "fundamental-payroll-gin/model"

	mock "github.com/stretchr/testify/mock"
)

// PayrollRepositoryI is an autogenerated mock type for the PayrollRepositoryI type
type PayrollRepositoryI struct {
	mock.Mock
}

// Detail provides a mock function with given fields: id
func (_m *PayrollRepositoryI) Detail(id int64) (*model.Payroll, error) {
	ret := _m.Called(id)

	var r0 *model.Payroll
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*model.Payroll, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *model.Payroll); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Payroll)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields:
func (_m *PayrollRepositoryI) List() ([]model.Payroll, error) {
	ret := _m.Called()

	var r0 []model.Payroll
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]model.Payroll, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []model.Payroll); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Payroll)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPayrollRepositoryI interface {
	mock.TestingT
	Cleanup(func())
}

// NewPayrollRepositoryI creates a new instance of PayrollRepositoryI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPayrollRepositoryI(t mockConstructorTestingTNewPayrollRepositoryI) *PayrollRepositoryI {
	mock := &PayrollRepositoryI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
